name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: g++ -o sudo_site sudo_site.cpp -lstdc++fs
    - name: build
      run: ./sudo_site
    - name: Push changes to the sudo_site_demo repository
      run: |
       ls
       git clone https://${{ secrets.MYTOKEN }}@github.com/sharadcodes/sudo_site_demo.git
       cp -a site/. sudo_site_demo
       cd sudo_site_demo
       ls
       git config user.email "${{ github.actor }}@users.noreply.github.com"
       git config user.name "${{ github.actor }}"        
       git add .
       git commit -am "Site updated"
       git push -f -q https://${{ secrets.MYTOKEN }}@github.com/sharadcodes/sudo_site_demo.git master
       echo Finished hard
      
